spring:
  application:
    name: atm-service
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
    continue-on-error: true
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://pgsql-db-01:5432/atm
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      schema: public
jwt:
  secret: vasof!N+T&!C8eW&RaFE
